import type { FunctionUnit } from "../types";

export const temperatureUnits: FunctionUnit[] = [
  {
    id: "celsius",
    name: "Celsius",
    symbol: "\u00B0C",
    aliases: ["c", "centigrade"],
    category: "temperature",
    toBase: (v) => v,
    fromBase: (v) => v,
  },
  {
    id: "fahrenheit",
    name: "Fahrenheit",
    symbol: "\u00B0F",
    aliases: ["f"],
    category: "temperature",
    toBase: (v) => (v - 32) * (5 / 9),
    fromBase: (v) => v * (9 / 5) + 32,
  },
  {
    id: "kelvin",
    name: "Kelvin",
    symbol: "K",
    aliases: ["k"],
    category: "temperature",
    toBase: (v) => v - 273.15,
    fromBase: (v) => v + 273.15,
  },
  {
    id: "rankine",
    name: "Rankine",
    symbol: "\u00B0R",
    aliases: ["r", "rankines"],
    category: "temperature",
    toBase: (v) => (v - 491.67) * (5 / 9),
    fromBase: (v) => v * (9 / 5) + 491.67,
  },
  {
    id: "delisle",
    name: "Delisle",
    symbol: "\u00B0De",
    aliases: ["de"],
    category: "temperature",
    toBase: (v) => 100 - v * (2 / 3),
    fromBase: (v) => (100 - v) * (3 / 2),
  },
  {
    id: "newton-temp",
    name: "Newton (temp)",
    symbol: "\u00B0N",
    aliases: ["newton temperature"],
    category: "temperature",
    toBase: (v) => v * (100 / 33),
    fromBase: (v) => v * (33 / 100),
  },
  {
    id: "reaumur",
    name: "R\u00E9aumur",
    symbol: "\u00B0R\u00E9",
    aliases: ["reaumur"],
    category: "temperature",
    toBase: (v) => v * (5 / 4),
    fromBase: (v) => v * (4 / 5),
  },
  {
    id: "romer",
    name: "R\u00F8mer",
    symbol: "\u00B0R\u00F8",
    aliases: ["romer"],
    category: "temperature",
    toBase: (v) => (v - 7.5) * (40 / 21),
    fromBase: (v) => v * (21 / 40) + 7.5,
  },
];
