import type { Element } from "./types";

/**
 * Complete periodic table dataset — 118 elements with ~30 properties each.
 * Sources: IUPAC, NIST, WebElements, PubChem.
 *
 * Grid positions: gridRow/gridCol use 0-indexed coordinates.
 * Rows 0-6 = main table (periods 1-7)
 * Row 7 = gap (empty)
 * Row 8 = lanthanides (Ce-Lu, cols 2-15)
 * Row 9 = actinides (Th-Lr, cols 2-15)
 */
export const ELEMENTS: Element[] = [
  // ═══════════════════════════════════════════
  // Period 1
  // ═══════════════════════════════════════════
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    block: "s",
    group: 1,
    period: 1,
    electronConfiguration: "1s¹",
    electronShells: [1],
    electronegativity: 2.2,
    atomicRadius: 53,
    ionizationEnergy: 1312,
    electronAffinity: -73,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
    density: 0.00008988,
    stateAtRT: "gas",
    crystalStructure: "hexagonal",
    yearDiscovered: 1766,
    discoverer: "Henry Cavendish",
    nameOrigin: "Greek 'hydro genes' — water forming",
    uses: ["Rocket fuel", "Ammonia production", "Fuel cells", "Petroleum refining"],
    isotopes: [
      { massNumber: 1, abundance: 99.98, halfLife: null },
      { massNumber: 2, abundance: 0.02, halfLife: null },
      { massNumber: 3, abundance: null, halfLife: "12.32 years" },
    ],
    gridRow: 0,
    gridCol: 0,
  },
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble-gas",
    block: "s",
    group: 18,
    period: 1,
    electronConfiguration: "1s²",
    electronShells: [2],
    electronegativity: null,
    atomicRadius: 31,
    ionizationEnergy: 2372,
    electronAffinity: 0,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
    density: 0.0001785,
    stateAtRT: "gas",
    crystalStructure: "hcp",
    yearDiscovered: 1868,
    discoverer: "Pierre Janssen & Joseph Lockyer",
    nameOrigin: "Greek 'helios' — sun",
    uses: ["Balloons", "Cryogenics", "MRI machines", "Deep-sea diving gas"],
    isotopes: [
      { massNumber: 3, abundance: 0.0001, halfLife: null },
      { massNumber: 4, abundance: 99.9999, halfLife: null },
    ],
    gridRow: 0,
    gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 2
  // ═══════════════════════════════════════════
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.941,
    category: "alkali-metal",
    block: "s",
    group: 1,
    period: 2,
    electronConfiguration: "[He] 2s¹",
    electronShells: [2, 1],
    electronegativity: 0.98,
    atomicRadius: 167,
    ionizationEnergy: 520,
    electronAffinity: -60,
    meltingPoint: 453.69,
    boilingPoint: 1615,
    density: 0.534,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1817,
    discoverer: "Johan August Arfwedson",
    nameOrigin: "Greek 'lithos' — stone",
    uses: ["Batteries", "Ceramics", "Psychiatric medication", "Aerospace alloys"],
    isotopes: [
      { massNumber: 6, abundance: 7.59, halfLife: null },
      { massNumber: 7, abundance: 92.41, halfLife: null },
    ],
    gridRow: 1,
    gridCol: 0,
  },
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth-metal",
    block: "s",
    group: 2,
    period: 2,
    electronConfiguration: "[He] 2s²",
    electronShells: [2, 2],
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 900,
    electronAffinity: 0,
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1798,
    discoverer: "Louis Nicolas Vauquelin",
    nameOrigin: "Greek 'beryllos' — beryl mineral",
    uses: ["X-ray windows", "Aerospace alloys", "Nuclear reactors", "Speakers"],
    isotopes: [{ massNumber: 9, abundance: 100, halfLife: null }],
    gridRow: 1,
    gridCol: 1,
  },
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    block: "p",
    group: 13,
    period: 2,
    electronConfiguration: "[He] 2s² 2p¹",
    electronShells: [2, 3],
    electronegativity: 2.04,
    atomicRadius: 87,
    ionizationEnergy: 801,
    electronAffinity: -27,
    meltingPoint: 2349,
    boilingPoint: 4200,
    density: 2.34,
    stateAtRT: "solid",
    crystalStructure: "rhombohedral",
    yearDiscovered: 1808,
    discoverer: "Joseph Louis Gay-Lussac & Louis Jacques Thénard",
    nameOrigin: "Arabic 'buraq' — borax",
    uses: ["Borosilicate glass", "Detergents", "Semiconductors", "Insulation"],
    isotopes: [
      { massNumber: 10, abundance: 19.9, halfLife: null },
      { massNumber: 11, abundance: 80.1, halfLife: null },
    ],
    gridRow: 1,
    gridCol: 12,
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    block: "p",
    group: 14,
    period: 2,
    electronConfiguration: "[He] 2s² 2p²",
    electronShells: [2, 4],
    electronegativity: 2.55,
    atomicRadius: 77,
    ionizationEnergy: 1087,
    electronAffinity: -154,
    meltingPoint: 3823,
    boilingPoint: 4098,
    density: 2.267,
    stateAtRT: "solid",
    crystalStructure: "diamond-cubic",
    yearDiscovered: "Ancient",
    discoverer: null,
    nameOrigin: "Latin 'carbo' — charcoal",
    uses: ["Steel production", "Diamonds", "Graphite pencils", "Carbon fiber", "All organic chemistry"],
    isotopes: [
      { massNumber: 12, abundance: 98.93, halfLife: null },
      { massNumber: 13, abundance: 1.07, halfLife: null },
      { massNumber: 14, abundance: null, halfLife: "5730 years" },
    ],
    gridRow: 1,
    gridCol: 13,
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    block: "p",
    group: 15,
    period: 2,
    electronConfiguration: "[He] 2s² 2p³",
    electronShells: [2, 5],
    electronegativity: 3.04,
    atomicRadius: 75,
    ionizationEnergy: 1402,
    electronAffinity: -7,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
    density: 0.0012506,
    stateAtRT: "gas",
    crystalStructure: "hexagonal",
    yearDiscovered: 1772,
    discoverer: "Daniel Rutherford",
    nameOrigin: "Greek 'nitron genes' — niter forming",
    uses: ["Fertilizers", "Explosives", "Food preservation", "Cryogenics"],
    isotopes: [
      { massNumber: 14, abundance: 99.63, halfLife: null },
      { massNumber: 15, abundance: 0.37, halfLife: null },
    ],
    gridRow: 1,
    gridCol: 14,
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    block: "p",
    group: 16,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁴",
    electronShells: [2, 6],
    electronegativity: 3.44,
    atomicRadius: 73,
    ionizationEnergy: 1314,
    electronAffinity: -141,
    meltingPoint: 54.36,
    boilingPoint: 90.2,
    density: 0.001429,
    stateAtRT: "gas",
    crystalStructure: "simple-cubic",
    yearDiscovered: 1774,
    discoverer: "Joseph Priestley & Carl Wilhelm Scheele",
    nameOrigin: "Greek 'oxy genes' — acid forming",
    uses: ["Respiration", "Steel production", "Water treatment", "Welding"],
    isotopes: [
      { massNumber: 16, abundance: 99.76, halfLife: null },
      { massNumber: 17, abundance: 0.04, halfLife: null },
      { massNumber: 18, abundance: 0.20, halfLife: null },
    ],
    gridRow: 1,
    gridCol: 15,
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "halogen",
    block: "p",
    group: 17,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁵",
    electronShells: [2, 7],
    electronegativity: 3.98,
    atomicRadius: 71,
    ionizationEnergy: 1681,
    electronAffinity: -328,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
    density: 0.001696,
    stateAtRT: "gas",
    crystalStructure: "simple-cubic",
    yearDiscovered: 1886,
    discoverer: "Henri Moissan",
    nameOrigin: "Latin 'fluere' — to flow",
    uses: ["Toothpaste", "Teflon", "Refrigerants", "Uranium enrichment"],
    isotopes: [{ massNumber: 19, abundance: 100, halfLife: null }],
    gridRow: 1,
    gridCol: 16,
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "noble-gas",
    block: "p",
    group: 18,
    period: 2,
    electronConfiguration: "[He] 2s² 2p⁶",
    electronShells: [2, 8],
    electronegativity: null,
    atomicRadius: 38,
    ionizationEnergy: 2081,
    electronAffinity: 0,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
    density: 0.0008999,
    stateAtRT: "gas",
    crystalStructure: "fcc",
    yearDiscovered: 1898,
    discoverer: "William Ramsay & Morris Travers",
    nameOrigin: "Greek 'neos' — new",
    uses: ["Neon signs", "Lasers", "Cryogenics", "Television tubes"],
    isotopes: [
      { massNumber: 20, abundance: 90.48, halfLife: null },
      { massNumber: 21, abundance: 0.27, halfLife: null },
      { massNumber: 22, abundance: 9.25, halfLife: null },
    ],
    gridRow: 1,
    gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 3
  // ═══════════════════════════════════════════
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "alkali-metal",
    block: "s",
    group: 1,
    period: 3,
    electronConfiguration: "[Ne] 3s¹",
    electronShells: [2, 8, 1],
    electronegativity: 0.93,
    atomicRadius: 190,
    ionizationEnergy: 496,
    electronAffinity: -53,
    meltingPoint: 370.87,
    boilingPoint: 1156,
    density: 0.971,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1807,
    discoverer: "Humphry Davy",
    nameOrigin: "Latin 'natrium' — from soda",
    uses: ["Table salt", "Street lamps", "Chemical reagent", "Nuclear reactors"],
    isotopes: [{ massNumber: 23, abundance: 100, halfLife: null }],
    gridRow: 2,
    gridCol: 0,
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth-metal",
    block: "s",
    group: 2,
    period: 3,
    electronConfiguration: "[Ne] 3s²",
    electronShells: [2, 8, 2],
    electronegativity: 1.31,
    atomicRadius: 145,
    ionizationEnergy: 738,
    electronAffinity: 0,
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1808,
    discoverer: "Humphry Davy",
    nameOrigin: "Magnesia, a district in Greece",
    uses: ["Alloys", "Fireworks", "Antacids", "Aerospace components"],
    isotopes: [
      { massNumber: 24, abundance: 78.99, halfLife: null },
      { massNumber: 25, abundance: 10.00, halfLife: null },
      { massNumber: 26, abundance: 11.01, halfLife: null },
    ],
    gridRow: 2,
    gridCol: 1,
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition-metal",
    block: "p",
    group: 13,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p¹",
    electronShells: [2, 8, 3],
    electronegativity: 1.61,
    atomicRadius: 118,
    ionizationEnergy: 578,
    electronAffinity: -43,
    meltingPoint: 933.47,
    boilingPoint: 2792,
    density: 2.698,
    stateAtRT: "solid",
    crystalStructure: "fcc",
    yearDiscovered: 1825,
    discoverer: "Hans Christian Ørsted",
    nameOrigin: "Latin 'alumen' — alum",
    uses: ["Cans", "Foil", "Aircraft", "Window frames", "Electrical wiring"],
    isotopes: [{ massNumber: 27, abundance: 100, halfLife: null }],
    gridRow: 2,
    gridCol: 12,
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.086,
    category: "metalloid",
    block: "p",
    group: 14,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p²",
    electronShells: [2, 8, 4],
    electronegativity: 1.9,
    atomicRadius: 111,
    ionizationEnergy: 786,
    electronAffinity: -134,
    meltingPoint: 1687,
    boilingPoint: 3538,
    density: 2.3296,
    stateAtRT: "solid",
    crystalStructure: "diamond-cubic",
    yearDiscovered: 1824,
    discoverer: "Jöns Jacob Berzelius",
    nameOrigin: "Latin 'silex' — flint",
    uses: ["Computer chips", "Solar cells", "Glass", "Silicone", "Semiconductors"],
    isotopes: [
      { massNumber: 28, abundance: 92.23, halfLife: null },
      { massNumber: 29, abundance: 4.68, halfLife: null },
      { massNumber: 30, abundance: 3.09, halfLife: null },
    ],
    gridRow: 2,
    gridCol: 13,
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    block: "p",
    group: 15,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p³",
    electronShells: [2, 8, 5],
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 1012,
    electronAffinity: -72,
    meltingPoint: 317.3,
    boilingPoint: 553.65,
    density: 1.82,
    stateAtRT: "solid",
    crystalStructure: "simple-cubic",
    yearDiscovered: 1669,
    discoverer: "Hennig Brand",
    nameOrigin: "Greek 'phosphoros' — light-bearing",
    uses: ["Fertilizers", "Matches", "Detergents", "Steel production"],
    isotopes: [{ massNumber: 31, abundance: 100, halfLife: null }],
    gridRow: 2,
    gridCol: 14,
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    block: "p",
    group: 16,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁴",
    electronShells: [2, 8, 6],
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 1000,
    electronAffinity: -200,
    meltingPoint: 388.36,
    boilingPoint: 717.87,
    density: 2.067,
    stateAtRT: "solid",
    crystalStructure: "orthorhombic",
    yearDiscovered: "Ancient",
    discoverer: null,
    nameOrigin: "Latin 'sulphur'",
    uses: ["Sulfuric acid", "Vulcanizing rubber", "Gunpowder", "Fertilizers"],
    isotopes: [
      { massNumber: 32, abundance: 94.93, halfLife: null },
      { massNumber: 33, abundance: 0.76, halfLife: null },
      { massNumber: 34, abundance: 4.29, halfLife: null },
      { massNumber: 36, abundance: 0.02, halfLife: null },
    ],
    gridRow: 2,
    gridCol: 15,
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "halogen",
    block: "p",
    group: 17,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁵",
    electronShells: [2, 8, 7],
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 1251,
    electronAffinity: -349,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    density: 0.003214,
    stateAtRT: "gas",
    crystalStructure: "orthorhombic",
    yearDiscovered: 1774,
    discoverer: "Carl Wilhelm Scheele",
    nameOrigin: "Greek 'chloros' — greenish-yellow",
    uses: ["Water purification", "PVC plastic", "Bleach", "Disinfectants"],
    isotopes: [
      { massNumber: 35, abundance: 75.76, halfLife: null },
      { massNumber: 37, abundance: 24.24, halfLife: null },
    ],
    gridRow: 2,
    gridCol: 16,
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "noble-gas",
    block: "p",
    group: 18,
    period: 3,
    electronConfiguration: "[Ne] 3s² 3p⁶",
    electronShells: [2, 8, 8],
    electronegativity: null,
    atomicRadius: 71,
    ionizationEnergy: 1521,
    electronAffinity: 0,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
    density: 0.0017837,
    stateAtRT: "gas",
    crystalStructure: "fcc",
    yearDiscovered: 1894,
    discoverer: "Lord Rayleigh & William Ramsay",
    nameOrigin: "Greek 'argon' — inactive",
    uses: ["Welding shield gas", "Light bulbs", "Double-pane windows", "Lasers"],
    isotopes: [
      { massNumber: 36, abundance: 0.34, halfLife: null },
      { massNumber: 38, abundance: 0.06, halfLife: null },
      { massNumber: 40, abundance: 99.6, halfLife: null },
    ],
    gridRow: 2,
    gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 4
  // ═══════════════════════════════════════════
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    block: "s",
    group: 1,
    period: 4,
    electronConfiguration: "[Ar] 4s¹",
    electronShells: [2, 8, 8, 1],
    electronegativity: 0.82,
    atomicRadius: 243,
    ionizationEnergy: 419,
    electronAffinity: -48,
    meltingPoint: 336.53,
    boilingPoint: 1032,
    density: 0.862,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1807,
    discoverer: "Humphry Davy",
    nameOrigin: "English 'potash'; symbol from Latin 'kalium'",
    uses: ["Fertilizers", "Soap", "Glass", "Food preservation"],
    isotopes: [
      { massNumber: 39, abundance: 93.26, halfLife: null },
      { massNumber: 40, abundance: 0.012, halfLife: "1.25 billion years" },
      { massNumber: 41, abundance: 6.73, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 0,
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth-metal",
    block: "s",
    group: 2,
    period: 4,
    electronConfiguration: "[Ar] 4s²",
    electronShells: [2, 8, 8, 2],
    electronegativity: 1.0,
    atomicRadius: 194,
    ionizationEnergy: 590,
    electronAffinity: -2,
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.54,
    stateAtRT: "solid",
    crystalStructure: "fcc",
    yearDiscovered: 1808,
    discoverer: "Humphry Davy",
    nameOrigin: "Latin 'calx' — lime",
    uses: ["Cement", "Cheese making", "Bones and teeth", "Steel production"],
    isotopes: [
      { massNumber: 40, abundance: 96.94, halfLife: null },
      { massNumber: 42, abundance: 0.65, halfLife: null },
      { massNumber: 43, abundance: 0.14, halfLife: null },
      { massNumber: 44, abundance: 2.09, halfLife: null },
      { massNumber: 46, abundance: 0.004, halfLife: null },
      { massNumber: 48, abundance: 0.19, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 1,
  },
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition-metal",
    block: "d",
    group: 3,
    period: 4,
    electronConfiguration: "[Ar] 3d¹ 4s²",
    electronShells: [2, 8, 9, 2],
    electronegativity: 1.36,
    atomicRadius: 184,
    ionizationEnergy: 633,
    electronAffinity: -18,
    meltingPoint: 1814,
    boilingPoint: 3109,
    density: 2.989,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1879,
    discoverer: "Lars Fredrik Nilson",
    nameOrigin: "Latin 'Scandia' — Scandinavia",
    uses: ["Aerospace alloys", "Sports equipment", "Lighting", "Laser crystals"],
    isotopes: [{ massNumber: 45, abundance: 100, halfLife: null }],
    gridRow: 3,
    gridCol: 2,
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition-metal",
    block: "d",
    group: 4,
    period: 4,
    electronConfiguration: "[Ar] 3d² 4s²",
    electronShells: [2, 8, 10, 2],
    electronegativity: 1.54,
    atomicRadius: 176,
    ionizationEnergy: 659,
    electronAffinity: -8,
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.54,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1791,
    discoverer: "William Gregor",
    nameOrigin: "Greek 'Titans' — mythological",
    uses: ["Aircraft", "Implants", "Paint pigment", "Jewelry"],
    isotopes: [
      { massNumber: 46, abundance: 8.25, halfLife: null },
      { massNumber: 47, abundance: 7.44, halfLife: null },
      { massNumber: 48, abundance: 73.72, halfLife: null },
      { massNumber: 49, abundance: 5.41, halfLife: null },
      { massNumber: 50, abundance: 5.18, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 3,
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition-metal",
    block: "d",
    group: 5,
    period: 4,
    electronConfiguration: "[Ar] 3d³ 4s²",
    electronShells: [2, 8, 11, 2],
    electronegativity: 1.63,
    atomicRadius: 171,
    ionizationEnergy: 651,
    electronAffinity: -51,
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6.11,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1801,
    discoverer: "Andrés Manuel del Río",
    nameOrigin: "Vanadis, Norse goddess of beauty",
    uses: ["Steel alloys", "Jet engines", "Vanadium redox batteries", "Catalysts"],
    isotopes: [
      { massNumber: 50, abundance: 0.25, halfLife: null },
      { massNumber: 51, abundance: 99.75, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 4,
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition-metal",
    block: "d",
    group: 6,
    period: 4,
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    electronShells: [2, 8, 13, 1],
    electronegativity: 1.66,
    atomicRadius: 166,
    ionizationEnergy: 653,
    electronAffinity: -64,
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.15,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1797,
    discoverer: "Louis Nicolas Vauquelin",
    nameOrigin: "Greek 'chroma' — color",
    uses: ["Stainless steel", "Chrome plating", "Dyes and pigments", "Leather tanning"],
    isotopes: [
      { massNumber: 50, abundance: 4.35, halfLife: null },
      { massNumber: 52, abundance: 83.79, halfLife: null },
      { massNumber: 53, abundance: 9.50, halfLife: null },
      { massNumber: 54, abundance: 2.37, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 5,
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition-metal",
    block: "d",
    group: 7,
    period: 4,
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    electronShells: [2, 8, 13, 2],
    electronegativity: 1.55,
    atomicRadius: 161,
    ionizationEnergy: 717,
    electronAffinity: 0,
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.44,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: 1774,
    discoverer: "Johan Gottlieb Gahn",
    nameOrigin: "Latin 'magnes' — magnet",
    uses: ["Steel production", "Batteries", "Aluminum alloys", "Water treatment"],
    isotopes: [{ massNumber: 55, abundance: 100, halfLife: null }],
    gridRow: 3,
    gridCol: 6,
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    block: "d",
    group: 8,
    period: 4,
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    electronShells: [2, 8, 14, 2],
    electronegativity: 1.83,
    atomicRadius: 156,
    ionizationEnergy: 762,
    electronAffinity: -16,
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    stateAtRT: "solid",
    crystalStructure: "bcc",
    yearDiscovered: "Ancient",
    discoverer: null,
    nameOrigin: "Anglo-Saxon 'iron'; symbol from Latin 'ferrum'",
    uses: ["Steel", "Construction", "Automobiles", "Magnets", "Cookware"],
    isotopes: [
      { massNumber: 54, abundance: 5.85, halfLife: null },
      { massNumber: 56, abundance: 91.75, halfLife: null },
      { massNumber: 57, abundance: 2.12, halfLife: null },
      { massNumber: 58, abundance: 0.28, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 7,
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition-metal",
    block: "d",
    group: 9,
    period: 4,
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    electronShells: [2, 8, 15, 2],
    electronegativity: 1.88,
    atomicRadius: 152,
    ionizationEnergy: 760,
    electronAffinity: -64,
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.86,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1735,
    discoverer: "Georg Brandt",
    nameOrigin: "German 'kobald' — goblin",
    uses: ["Superalloys", "Magnets", "Blue pigment", "Batteries", "Cancer treatment"],
    isotopes: [{ massNumber: 59, abundance: 100, halfLife: null }],
    gridRow: 3,
    gridCol: 8,
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition-metal",
    block: "d",
    group: 10,
    period: 4,
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    electronShells: [2, 8, 16, 2],
    electronegativity: 1.91,
    atomicRadius: 149,
    ionizationEnergy: 737,
    electronAffinity: -112,
    meltingPoint: 1728,
    boilingPoint: 3186,
    density: 8.912,
    stateAtRT: "solid",
    crystalStructure: "fcc",
    yearDiscovered: 1751,
    discoverer: "Axel Fredrik Cronstedt",
    nameOrigin: "German 'Kupfernickel' — devil's copper",
    uses: ["Stainless steel", "Coins", "Batteries", "Electroplating"],
    isotopes: [
      { massNumber: 58, abundance: 68.08, halfLife: null },
      { massNumber: 60, abundance: 26.22, halfLife: null },
      { massNumber: 61, abundance: 1.14, halfLife: null },
      { massNumber: 62, abundance: 3.63, halfLife: null },
      { massNumber: 64, abundance: 0.93, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 9,
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    block: "d",
    group: 11,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    electronShells: [2, 8, 18, 1],
    electronegativity: 1.9,
    atomicRadius: 145,
    ionizationEnergy: 745,
    electronAffinity: -119,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    density: 8.96,
    stateAtRT: "solid",
    crystalStructure: "fcc",
    yearDiscovered: "Ancient",
    discoverer: null,
    nameOrigin: "Latin 'cuprum' — from Cyprus",
    uses: ["Electrical wiring", "Plumbing", "Coins", "Circuit boards"],
    isotopes: [
      { massNumber: 63, abundance: 69.17, halfLife: null },
      { massNumber: 65, abundance: 30.83, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 10,
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    block: "d",
    group: 12,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    electronShells: [2, 8, 18, 2],
    electronegativity: 1.65,
    atomicRadius: 142,
    ionizationEnergy: 906,
    electronAffinity: 0,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    density: 7.134,
    stateAtRT: "solid",
    crystalStructure: "hcp",
    yearDiscovered: 1746,
    discoverer: "Andreas Sigismund Marggraf",
    nameOrigin: "German 'Zinke' — prong/tooth",
    uses: ["Galvanizing steel", "Batteries", "Brass alloy", "Sunscreen"],
    isotopes: [
      { massNumber: 64, abundance: 48.63, halfLife: null },
      { massNumber: 66, abundance: 27.90, halfLife: null },
      { massNumber: 67, abundance: 4.10, halfLife: null },
      { massNumber: 68, abundance: 18.75, halfLife: null },
      { massNumber: 70, abundance: 0.62, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 11,
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition-metal",
    block: "p",
    group: 13,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronShells: [2, 8, 18, 3],
    electronegativity: 1.81,
    atomicRadius: 136,
    ionizationEnergy: 579,
    electronAffinity: -29,
    meltingPoint: 302.91,
    boilingPoint: 2477,
    density: 5.907,
    stateAtRT: "solid",
    crystalStructure: "orthorhombic",
    yearDiscovered: 1875,
    discoverer: "Paul Emile Lecoq de Boisbaudran",
    nameOrigin: "Latin 'Gallia' — France",
    uses: ["Semiconductors", "LEDs", "Solar cells", "Thermometers"],
    isotopes: [
      { massNumber: 69, abundance: 60.11, halfLife: null },
      { massNumber: 71, abundance: 39.89, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 12,
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "metalloid",
    block: "p",
    group: 14,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronShells: [2, 8, 18, 4],
    electronegativity: 2.01,
    atomicRadius: 125,
    ionizationEnergy: 762,
    electronAffinity: -119,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    density: 5.323,
    stateAtRT: "solid",
    crystalStructure: "diamond-cubic",
    yearDiscovered: 1886,
    discoverer: "Clemens Winkler",
    nameOrigin: "Latin 'Germania' — Germany",
    uses: ["Fiber optics", "Infrared optics", "Transistors", "Solar cells"],
    isotopes: [
      { massNumber: 70, abundance: 20.84, halfLife: null },
      { massNumber: 72, abundance: 27.54, halfLife: null },
      { massNumber: 73, abundance: 7.73, halfLife: null },
      { massNumber: 74, abundance: 36.28, halfLife: null },
      { massNumber: 76, abundance: 7.61, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 13,
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    block: "p",
    group: 15,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronShells: [2, 8, 18, 5],
    electronegativity: 2.18,
    atomicRadius: 114,
    ionizationEnergy: 947,
    electronAffinity: -78,
    meltingPoint: 1090,
    boilingPoint: 887,
    density: 5.776,
    stateAtRT: "solid",
    crystalStructure: "rhombohedral",
    yearDiscovered: 1250,
    discoverer: "Albertus Magnus",
    nameOrigin: "Greek 'arsenikon' — potent",
    uses: ["Semiconductors", "Wood preservative", "Lead alloys", "Pesticides"],
    isotopes: [{ massNumber: 75, abundance: 100, halfLife: null }],
    gridRow: 3,
    gridCol: 14,
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    block: "p",
    group: 16,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronShells: [2, 8, 18, 6],
    electronegativity: 2.55,
    atomicRadius: 103,
    ionizationEnergy: 941,
    electronAffinity: -195,
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.809,
    stateAtRT: "solid",
    crystalStructure: "hexagonal",
    yearDiscovered: 1817,
    discoverer: "Jöns Jacob Berzelius",
    nameOrigin: "Greek 'selene' — moon",
    uses: ["Solar cells", "Glass decolorizer", "Photocopiers", "Dietary supplement"],
    isotopes: [
      { massNumber: 74, abundance: 0.89, halfLife: null },
      { massNumber: 76, abundance: 9.37, halfLife: null },
      { massNumber: 77, abundance: 7.63, halfLife: null },
      { massNumber: 78, abundance: 23.77, halfLife: null },
      { massNumber: 80, abundance: 49.61, halfLife: null },
      { massNumber: 82, abundance: 8.73, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 15,
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "halogen",
    block: "p",
    group: 17,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronShells: [2, 8, 18, 7],
    electronegativity: 2.96,
    atomicRadius: 94,
    ionizationEnergy: 1140,
    electronAffinity: -325,
    meltingPoint: 265.8,
    boilingPoint: 332,
    density: 3.122,
    stateAtRT: "liquid",
    crystalStructure: "orthorhombic",
    yearDiscovered: 1826,
    discoverer: "Antoine Jérôme Balard",
    nameOrigin: "Greek 'bromos' — stench",
    uses: ["Flame retardants", "Photography", "Water purification", "Pharmaceuticals"],
    isotopes: [
      { massNumber: 79, abundance: 50.69, halfLife: null },
      { massNumber: 81, abundance: 49.31, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 16,
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble-gas",
    block: "p",
    group: 18,
    period: 4,
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronShells: [2, 8, 18, 8],
    electronegativity: 3.0,
    atomicRadius: 88,
    ionizationEnergy: 1351,
    electronAffinity: 0,
    meltingPoint: 115.79,
    boilingPoint: 119.93,
    density: 0.003733,
    stateAtRT: "gas",
    crystalStructure: "fcc",
    yearDiscovered: 1898,
    discoverer: "William Ramsay & Morris Travers",
    nameOrigin: "Greek 'kryptos' — hidden",
    uses: ["Photography flash", "Fluorescent lighting", "Lasers", "Insulation"],
    isotopes: [
      { massNumber: 78, abundance: 0.36, halfLife: null },
      { massNumber: 80, abundance: 2.29, halfLife: null },
      { massNumber: 82, abundance: 11.59, halfLife: null },
      { massNumber: 83, abundance: 11.50, halfLife: null },
      { massNumber: 84, abundance: 57.00, halfLife: null },
      { massNumber: 86, abundance: 17.28, halfLife: null },
    ],
    gridRow: 3,
    gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 5
  // ═══════════════════════════════════════════
  {
    atomicNumber: 37, symbol: "Rb", name: "Rubidium", atomicMass: 85.468, category: "alkali-metal", block: "s", group: 1, period: 5, electronConfiguration: "[Kr] 5s¹", electronShells: [2, 8, 18, 8, 1], electronegativity: 0.82, atomicRadius: 265, ionizationEnergy: 403, electronAffinity: -47, meltingPoint: 312.46, boilingPoint: 961, density: 1.532, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1861, discoverer: "Robert Bunsen & Gustav Kirchhoff", nameOrigin: "Latin 'rubidus' — dark red", uses: ["Atomic clocks", "Fireworks", "Photocells", "Research"], isotopes: [{ massNumber: 85, abundance: 72.17, halfLife: null }, { massNumber: 87, abundance: 27.83, halfLife: "49.23 billion years" }], gridRow: 4, gridCol: 0,
  },
  {
    atomicNumber: 38, symbol: "Sr", name: "Strontium", atomicMass: 87.62, category: "alkaline-earth-metal", block: "s", group: 2, period: 5, electronConfiguration: "[Kr] 5s²", electronShells: [2, 8, 18, 8, 2], electronegativity: 0.95, atomicRadius: 219, ionizationEnergy: 550, electronAffinity: -5, meltingPoint: 1050, boilingPoint: 1655, density: 2.64, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1790, discoverer: "Adair Crawford", nameOrigin: "Strontian, Scotland", uses: ["Fireworks (red)", "CRT televisions", "Magnets", "Toothpaste"], isotopes: [{ massNumber: 84, abundance: 0.56, halfLife: null }, { massNumber: 86, abundance: 9.86, halfLife: null }, { massNumber: 87, abundance: 7.00, halfLife: null }, { massNumber: 88, abundance: 82.58, halfLife: null }], gridRow: 4, gridCol: 1,
  },
  {
    atomicNumber: 39, symbol: "Y", name: "Yttrium", atomicMass: 88.906, category: "transition-metal", block: "d", group: 3, period: 5, electronConfiguration: "[Kr] 4d¹ 5s²", electronShells: [2, 8, 18, 9, 2], electronegativity: 1.22, atomicRadius: 212, ionizationEnergy: 600, electronAffinity: -30, meltingPoint: 1799, boilingPoint: 3609, density: 4.469, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1794, discoverer: "Johan Gadolin", nameOrigin: "Ytterby, Sweden", uses: ["LED phosphors", "Superconductors", "Lasers", "Cancer treatment"], isotopes: [{ massNumber: 89, abundance: 100, halfLife: null }], gridRow: 4, gridCol: 2,
  },
  {
    atomicNumber: 40, symbol: "Zr", name: "Zirconium", atomicMass: 91.224, category: "transition-metal", block: "d", group: 4, period: 5, electronConfiguration: "[Kr] 4d² 5s²", electronShells: [2, 8, 18, 10, 2], electronegativity: 1.33, atomicRadius: 206, ionizationEnergy: 640, electronAffinity: -41, meltingPoint: 2128, boilingPoint: 4682, density: 6.506, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1789, discoverer: "Martin Heinrich Klaproth", nameOrigin: "Persian 'zargun' — gold-colored", uses: ["Nuclear reactors", "Ceramics", "Surgical instruments", "Cubic zirconia"], isotopes: [{ massNumber: 90, abundance: 51.45, halfLife: null }, { massNumber: 91, abundance: 11.22, halfLife: null }, { massNumber: 92, abundance: 17.15, halfLife: null }, { massNumber: 94, abundance: 17.38, halfLife: null }, { massNumber: 96, abundance: 2.80, halfLife: null }], gridRow: 4, gridCol: 3,
  },
  {
    atomicNumber: 41, symbol: "Nb", name: "Niobium", atomicMass: 92.906, category: "transition-metal", block: "d", group: 5, period: 5, electronConfiguration: "[Kr] 4d⁴ 5s¹", electronShells: [2, 8, 18, 12, 1], electronegativity: 1.6, atomicRadius: 198, ionizationEnergy: 652, electronAffinity: -86, meltingPoint: 2750, boilingPoint: 5017, density: 8.57, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1801, discoverer: "Charles Hatchett", nameOrigin: "Greek 'Niobe' — daughter of Tantalus", uses: ["Superconducting magnets", "Steel alloys", "Jet engines", "MRI magnets"], isotopes: [{ massNumber: 93, abundance: 100, halfLife: null }], gridRow: 4, gridCol: 4,
  },
  {
    atomicNumber: 42, symbol: "Mo", name: "Molybdenum", atomicMass: 95.95, category: "transition-metal", block: "d", group: 6, period: 5, electronConfiguration: "[Kr] 4d⁵ 5s¹", electronShells: [2, 8, 18, 13, 1], electronegativity: 2.16, atomicRadius: 190, ionizationEnergy: 684, electronAffinity: -72, meltingPoint: 2896, boilingPoint: 4912, density: 10.22, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1781, discoverer: "Carl Wilhelm Scheele", nameOrigin: "Greek 'molybdos' — lead", uses: ["Steel alloys", "Catalysts", "Lubricants", "Electronics"], isotopes: [{ massNumber: 92, abundance: 14.77, halfLife: null }, { massNumber: 94, abundance: 9.23, halfLife: null }, { massNumber: 95, abundance: 15.90, halfLife: null }, { massNumber: 96, abundance: 16.68, halfLife: null }, { massNumber: 97, abundance: 9.56, halfLife: null }, { massNumber: 98, abundance: 24.19, halfLife: null }, { massNumber: 100, abundance: 9.67, halfLife: null }], gridRow: 4, gridCol: 5,
  },
  {
    atomicNumber: 43, symbol: "Tc", name: "Technetium", atomicMass: 98, category: "transition-metal", block: "d", group: 7, period: 5, electronConfiguration: "[Kr] 4d⁵ 5s²", electronShells: [2, 8, 18, 13, 2], electronegativity: 1.9, atomicRadius: 183, ionizationEnergy: 702, electronAffinity: -53, meltingPoint: 2430, boilingPoint: 4538, density: 11.5, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1937, discoverer: "Carlo Perrier & Emilio Segrè", nameOrigin: "Greek 'technetos' — artificial", uses: ["Medical imaging", "Nuclear medicine", "Radiography", "Research"], isotopes: [{ massNumber: 98, abundance: null, halfLife: "4.2 million years" }, { massNumber: 99, abundance: null, halfLife: "211,100 years" }], gridRow: 4, gridCol: 6,
  },
  {
    atomicNumber: 44, symbol: "Ru", name: "Ruthenium", atomicMass: 101.07, category: "transition-metal", block: "d", group: 8, period: 5, electronConfiguration: "[Kr] 4d⁷ 5s¹", electronShells: [2, 8, 18, 15, 1], electronegativity: 2.2, atomicRadius: 178, ionizationEnergy: 710, electronAffinity: -101, meltingPoint: 2607, boilingPoint: 4423, density: 12.37, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1844, discoverer: "Karl Ernst Claus", nameOrigin: "Latin 'Ruthenia' — Russia", uses: ["Electronics", "Catalysts", "Solar cells", "Hard disk drives"], isotopes: [{ massNumber: 96, abundance: 5.54, halfLife: null }, { massNumber: 98, abundance: 1.87, halfLife: null }, { massNumber: 99, abundance: 12.76, halfLife: null }, { massNumber: 100, abundance: 12.60, halfLife: null }, { massNumber: 101, abundance: 17.06, halfLife: null }, { massNumber: 102, abundance: 31.55, halfLife: null }, { massNumber: 104, abundance: 18.62, halfLife: null }], gridRow: 4, gridCol: 7,
  },
  {
    atomicNumber: 45, symbol: "Rh", name: "Rhodium", atomicMass: 102.91, category: "transition-metal", block: "d", group: 9, period: 5, electronConfiguration: "[Kr] 4d⁸ 5s¹", electronShells: [2, 8, 18, 16, 1], electronegativity: 2.28, atomicRadius: 173, ionizationEnergy: 720, electronAffinity: -110, meltingPoint: 2237, boilingPoint: 3968, density: 12.41, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1803, discoverer: "William Hyde Wollaston", nameOrigin: "Greek 'rhodon' — rose", uses: ["Catalytic converters", "Jewelry", "Mirrors", "Electrical contacts"], isotopes: [{ massNumber: 103, abundance: 100, halfLife: null }], gridRow: 4, gridCol: 8,
  },
  {
    atomicNumber: 46, symbol: "Pd", name: "Palladium", atomicMass: 106.42, category: "transition-metal", block: "d", group: 10, period: 5, electronConfiguration: "[Kr] 4d¹⁰", electronShells: [2, 8, 18, 18], electronegativity: 2.2, atomicRadius: 169, ionizationEnergy: 804, electronAffinity: -54, meltingPoint: 1828.05, boilingPoint: 3236, density: 12.02, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1803, discoverer: "William Hyde Wollaston", nameOrigin: "Asteroid Pallas", uses: ["Catalytic converters", "Electronics", "Dentistry", "Hydrogen purification"], isotopes: [{ massNumber: 102, abundance: 1.02, halfLife: null }, { massNumber: 104, abundance: 11.14, halfLife: null }, { massNumber: 105, abundance: 22.33, halfLife: null }, { massNumber: 106, abundance: 27.33, halfLife: null }, { massNumber: 108, abundance: 26.46, halfLife: null }, { massNumber: 110, abundance: 11.72, halfLife: null }], gridRow: 4, gridCol: 9,
  },
  {
    atomicNumber: 47, symbol: "Ag", name: "Silver", atomicMass: 107.87, category: "transition-metal", block: "d", group: 11, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s¹", electronShells: [2, 8, 18, 18, 1], electronegativity: 1.93, atomicRadius: 165, ionizationEnergy: 731, electronAffinity: -126, meltingPoint: 1234.93, boilingPoint: 2435, density: 10.501, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Anglo-Saxon 'seolfor'; symbol from Latin 'argentum'", uses: ["Jewelry", "Photography", "Electronics", "Mirrors", "Antibacterials"], isotopes: [{ massNumber: 107, abundance: 51.84, halfLife: null }, { massNumber: 109, abundance: 48.16, halfLife: null }], gridRow: 4, gridCol: 10,
  },
  {
    atomicNumber: 48, symbol: "Cd", name: "Cadmium", atomicMass: 112.41, category: "transition-metal", block: "d", group: 12, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s²", electronShells: [2, 8, 18, 18, 2], electronegativity: 1.69, atomicRadius: 161, ionizationEnergy: 868, electronAffinity: 0, meltingPoint: 594.22, boilingPoint: 1040, density: 8.69, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1817, discoverer: "Friedrich Stromeyer", nameOrigin: "Latin 'cadmia' — calamine", uses: ["Batteries (NiCd)", "Pigments", "Coatings", "Nuclear reactors"], isotopes: [{ massNumber: 106, abundance: 1.25, halfLife: null }, { massNumber: 108, abundance: 0.89, halfLife: null }, { massNumber: 110, abundance: 12.49, halfLife: null }, { massNumber: 111, abundance: 12.80, halfLife: null }, { massNumber: 112, abundance: 24.13, halfLife: null }, { massNumber: 113, abundance: 12.22, halfLife: null }, { massNumber: 114, abundance: 28.73, halfLife: null }, { massNumber: 116, abundance: 7.49, halfLife: null }], gridRow: 4, gridCol: 11,
  },
  {
    atomicNumber: 49, symbol: "In", name: "Indium", atomicMass: 114.82, category: "post-transition-metal", block: "p", group: 13, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹", electronShells: [2, 8, 18, 18, 3], electronegativity: 1.78, atomicRadius: 156, ionizationEnergy: 558, electronAffinity: -29, meltingPoint: 429.75, boilingPoint: 2345, density: 7.31, stateAtRT: "solid", crystalStructure: "tetragonal", yearDiscovered: 1863, discoverer: "Ferdinand Reich & Hieronymous Theodor Richter", nameOrigin: "Latin 'indicum' — indigo spectral line", uses: ["Touchscreens (ITO)", "Solders", "Semiconductors", "Solar cells"], isotopes: [{ massNumber: 113, abundance: 4.29, halfLife: null }, { massNumber: 115, abundance: 95.71, halfLife: null }], gridRow: 4, gridCol: 12,
  },
  {
    atomicNumber: 50, symbol: "Sn", name: "Tin", atomicMass: 118.71, category: "post-transition-metal", block: "p", group: 14, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²", electronShells: [2, 8, 18, 18, 4], electronegativity: 1.96, atomicRadius: 145, ionizationEnergy: 709, electronAffinity: -107, meltingPoint: 505.08, boilingPoint: 2875, density: 7.287, stateAtRT: "solid", crystalStructure: "tetragonal", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Anglo-Saxon 'tin'; symbol from Latin 'stannum'", uses: ["Tin cans", "Solder", "Bronze alloy", "Window glass (float process)"], isotopes: [{ massNumber: 112, abundance: 0.97, halfLife: null }, { massNumber: 114, abundance: 0.66, halfLife: null }, { massNumber: 115, abundance: 0.34, halfLife: null }, { massNumber: 116, abundance: 14.54, halfLife: null }, { massNumber: 117, abundance: 7.68, halfLife: null }, { massNumber: 118, abundance: 24.22, halfLife: null }, { massNumber: 119, abundance: 8.59, halfLife: null }, { massNumber: 120, abundance: 32.58, halfLife: null }, { massNumber: 122, abundance: 4.63, halfLife: null }, { massNumber: 124, abundance: 5.79, halfLife: null }], gridRow: 4, gridCol: 13,
  },
  {
    atomicNumber: 51, symbol: "Sb", name: "Antimony", atomicMass: 121.76, category: "metalloid", block: "p", group: 15, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³", electronShells: [2, 8, 18, 18, 5], electronegativity: 2.05, atomicRadius: 133, ionizationEnergy: 834, electronAffinity: -103, meltingPoint: 903.78, boilingPoint: 1860, density: 6.685, stateAtRT: "solid", crystalStructure: "rhombohedral", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Greek 'anti + monos' — not alone; symbol from Latin 'stibium'", uses: ["Flame retardants", "Lead-acid batteries", "Semiconductors", "Pewter"], isotopes: [{ massNumber: 121, abundance: 57.21, halfLife: null }, { massNumber: 123, abundance: 42.79, halfLife: null }], gridRow: 4, gridCol: 14,
  },
  {
    atomicNumber: 52, symbol: "Te", name: "Tellurium", atomicMass: 127.6, category: "metalloid", block: "p", group: 16, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴", electronShells: [2, 8, 18, 18, 6], electronegativity: 2.1, atomicRadius: 123, ionizationEnergy: 869, electronAffinity: -190, meltingPoint: 722.66, boilingPoint: 1261, density: 6.232, stateAtRT: "solid", crystalStructure: "hexagonal", yearDiscovered: 1783, discoverer: "Franz-Joseph Müller von Reichenstein", nameOrigin: "Latin 'tellus' — earth", uses: ["Solar cells (CdTe)", "Thermoelectrics", "Alloys", "Rubber vulcanization"], isotopes: [{ massNumber: 120, abundance: 0.09, halfLife: null }, { massNumber: 122, abundance: 2.55, halfLife: null }, { massNumber: 123, abundance: 0.89, halfLife: null }, { massNumber: 124, abundance: 4.74, halfLife: null }, { massNumber: 125, abundance: 7.07, halfLife: null }, { massNumber: 126, abundance: 18.84, halfLife: null }, { massNumber: 128, abundance: 31.74, halfLife: null }, { massNumber: 130, abundance: 34.08, halfLife: null }], gridRow: 4, gridCol: 15,
  },
  {
    atomicNumber: 53, symbol: "I", name: "Iodine", atomicMass: 126.9, category: "halogen", block: "p", group: 17, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵", electronShells: [2, 8, 18, 18, 7], electronegativity: 2.66, atomicRadius: 115, ionizationEnergy: 1008, electronAffinity: -295, meltingPoint: 386.85, boilingPoint: 457.4, density: 4.93, stateAtRT: "solid", crystalStructure: "orthorhombic", yearDiscovered: 1811, discoverer: "Bernard Courtois", nameOrigin: "Greek 'iodes' — violet", uses: ["Disinfectants", "Thyroid treatment", "Photography", "LCD displays"], isotopes: [{ massNumber: 127, abundance: 100, halfLife: null }], gridRow: 4, gridCol: 16,
  },
  {
    atomicNumber: 54, symbol: "Xe", name: "Xenon", atomicMass: 131.29, category: "noble-gas", block: "p", group: 18, period: 5, electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶", electronShells: [2, 8, 18, 18, 8], electronegativity: 2.6, atomicRadius: 108, ionizationEnergy: 1170, electronAffinity: 0, meltingPoint: 161.36, boilingPoint: 165.03, density: 0.005887, stateAtRT: "gas", crystalStructure: "fcc", yearDiscovered: 1898, discoverer: "William Ramsay & Morris Travers", nameOrigin: "Greek 'xenon' — stranger", uses: ["Ion propulsion", "Anesthesia", "Headlights", "Flash lamps"], isotopes: [{ massNumber: 124, abundance: 0.09, halfLife: null }, { massNumber: 126, abundance: 0.09, halfLife: null }, { massNumber: 128, abundance: 1.92, halfLife: null }, { massNumber: 129, abundance: 26.44, halfLife: null }, { massNumber: 130, abundance: 4.08, halfLife: null }, { massNumber: 131, abundance: 21.18, halfLife: null }, { massNumber: 132, abundance: 26.89, halfLife: null }, { massNumber: 134, abundance: 10.44, halfLife: null }, { massNumber: 136, abundance: 8.87, halfLife: null }], gridRow: 4, gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 6
  // ═══════════════════════════════════════════
  {
    atomicNumber: 55, symbol: "Cs", name: "Cesium", atomicMass: 132.91, category: "alkali-metal", block: "s", group: 1, period: 6, electronConfiguration: "[Xe] 6s¹", electronShells: [2, 8, 18, 18, 8, 1], electronegativity: 0.79, atomicRadius: 298, ionizationEnergy: 376, electronAffinity: -46, meltingPoint: 301.59, boilingPoint: 944, density: 1.873, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1860, discoverer: "Robert Bunsen & Gustav Kirchhoff", nameOrigin: "Latin 'caesius' — sky blue", uses: ["Atomic clocks", "Photoelectric cells", "Drilling fluids", "Ion propulsion"], isotopes: [{ massNumber: 133, abundance: 100, halfLife: null }], gridRow: 5, gridCol: 0,
  },
  {
    atomicNumber: 56, symbol: "Ba", name: "Barium", atomicMass: 137.33, category: "alkaline-earth-metal", block: "s", group: 2, period: 6, electronConfiguration: "[Xe] 6s²", electronShells: [2, 8, 18, 18, 8, 2], electronegativity: 0.89, atomicRadius: 253, ionizationEnergy: 503, electronAffinity: -14, meltingPoint: 1000, boilingPoint: 2170, density: 3.594, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1808, discoverer: "Humphry Davy", nameOrigin: "Greek 'barys' — heavy", uses: ["X-ray contrast medium", "Fireworks (green)", "Oil drilling", "Glass"], isotopes: [{ massNumber: 130, abundance: 0.11, halfLife: null }, { massNumber: 132, abundance: 0.10, halfLife: null }, { massNumber: 134, abundance: 2.42, halfLife: null }, { massNumber: 135, abundance: 6.59, halfLife: null }, { massNumber: 136, abundance: 7.85, halfLife: null }, { massNumber: 137, abundance: 11.23, halfLife: null }, { massNumber: 138, abundance: 71.70, halfLife: null }], gridRow: 5, gridCol: 1,
  },
  // La placeholder in main table (gridRow 5, gridCol 2)
  {
    atomicNumber: 57, symbol: "La", name: "Lanthanum", atomicMass: 138.91, category: "lanthanide", block: "f", group: 3, period: 6, electronConfiguration: "[Xe] 5d¹ 6s²", electronShells: [2, 8, 18, 18, 9, 2], electronegativity: 1.1, atomicRadius: 250, ionizationEnergy: 538, electronAffinity: -50, meltingPoint: 1193, boilingPoint: 3737, density: 6.145, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1839, discoverer: "Carl Gustaf Mosander", nameOrigin: "Greek 'lanthanein' — to lie hidden", uses: ["Camera lenses", "Catalysts", "Lighter flints", "Hybrid car batteries"], isotopes: [{ massNumber: 138, abundance: 0.09, halfLife: null }, { massNumber: 139, abundance: 99.91, halfLife: null }], gridRow: 5, gridCol: 2,
  },
  {
    atomicNumber: 58, symbol: "Ce", name: "Cerium", atomicMass: 140.12, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²", electronShells: [2, 8, 18, 19, 9, 2], electronegativity: 1.12, atomicRadius: 248, ionizationEnergy: 534, electronAffinity: -50, meltingPoint: 1068, boilingPoint: 3716, density: 6.77, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1803, discoverer: "Jöns Jacob Berzelius & Wilhelm Hisinger", nameOrigin: "Asteroid Ceres", uses: ["Catalytic converters", "Glass polishing", "Self-cleaning ovens", "Lighter flints"], isotopes: [{ massNumber: 136, abundance: 0.19, halfLife: null }, { massNumber: 138, abundance: 0.25, halfLife: null }, { massNumber: 140, abundance: 88.45, halfLife: null }, { massNumber: 142, abundance: 11.11, halfLife: null }], gridRow: 8, gridCol: 3,
  },
  {
    atomicNumber: 59, symbol: "Pr", name: "Praseodymium", atomicMass: 140.91, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f³ 6s²", electronShells: [2, 8, 18, 21, 8, 2], electronegativity: 1.13, atomicRadius: 247, ionizationEnergy: 527, electronAffinity: -50, meltingPoint: 1208, boilingPoint: 3793, density: 6.773, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1885, discoverer: "Carl Auer von Welsbach", nameOrigin: "Greek 'prasios didymos' — green twin", uses: ["Magnets", "Aircraft engines", "Welder's goggles", "Yellow ceramic pigment"], isotopes: [{ massNumber: 141, abundance: 100, halfLife: null }], gridRow: 8, gridCol: 4,
  },
  {
    atomicNumber: 60, symbol: "Nd", name: "Neodymium", atomicMass: 144.24, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁴ 6s²", electronShells: [2, 8, 18, 22, 8, 2], electronegativity: 1.14, atomicRadius: 206, ionizationEnergy: 533, electronAffinity: -50, meltingPoint: 1297, boilingPoint: 3347, density: 7.007, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1885, discoverer: "Carl Auer von Welsbach", nameOrigin: "Greek 'neos didymos' — new twin", uses: ["Super-strong magnets (NdFeB)", "Lasers", "Electric motors", "Headphones"], isotopes: [{ massNumber: 142, abundance: 27.15, halfLife: null }, { massNumber: 143, abundance: 12.17, halfLife: null }, { massNumber: 144, abundance: 23.80, halfLife: null }, { massNumber: 145, abundance: 8.29, halfLife: null }, { massNumber: 146, abundance: 17.19, halfLife: null }, { massNumber: 148, abundance: 5.76, halfLife: null }, { massNumber: 150, abundance: 5.64, halfLife: null }], gridRow: 8, gridCol: 5,
  },
  {
    atomicNumber: 61, symbol: "Pm", name: "Promethium", atomicMass: 145, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁵ 6s²", electronShells: [2, 8, 18, 23, 8, 2], electronegativity: 1.13, atomicRadius: 205, ionizationEnergy: 540, electronAffinity: -50, meltingPoint: 1315, boilingPoint: 3273, density: 7.26, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1945, discoverer: "Jacob A. Marinsky, Lawrence E. Glendenin & Charles D. Coryell", nameOrigin: "Greek 'Prometheus' — mythological fire-bringer", uses: ["Nuclear batteries", "Luminous paint", "Thickness gauges", "Research"], isotopes: [{ massNumber: 145, abundance: null, halfLife: "17.7 years" }, { massNumber: 147, abundance: null, halfLife: "2.62 years" }], gridRow: 8, gridCol: 6,
  },
  {
    atomicNumber: 62, symbol: "Sm", name: "Samarium", atomicMass: 150.36, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁶ 6s²", electronShells: [2, 8, 18, 24, 8, 2], electronegativity: 1.17, atomicRadius: 238, ionizationEnergy: 545, electronAffinity: -50, meltingPoint: 1345, boilingPoint: 2067, density: 7.52, stateAtRT: "solid", crystalStructure: "rhombohedral", yearDiscovered: 1879, discoverer: "Paul Emile Lecoq de Boisbaudran", nameOrigin: "Mineral samarskite", uses: ["Magnets (SmCo)", "Nuclear reactors", "Cancer treatment", "Headphones"], isotopes: [{ massNumber: 144, abundance: 3.07, halfLife: null }, { massNumber: 147, abundance: 14.99, halfLife: null }, { massNumber: 148, abundance: 11.24, halfLife: null }, { massNumber: 149, abundance: 13.82, halfLife: null }, { massNumber: 150, abundance: 7.38, halfLife: null }, { massNumber: 152, abundance: 26.75, halfLife: null }, { massNumber: 154, abundance: 22.75, halfLife: null }], gridRow: 8, gridCol: 7,
  },
  {
    atomicNumber: 63, symbol: "Eu", name: "Europium", atomicMass: 151.96, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁷ 6s²", electronShells: [2, 8, 18, 25, 8, 2], electronegativity: 1.2, atomicRadius: 231, ionizationEnergy: 547, electronAffinity: -50, meltingPoint: 1099, boilingPoint: 1802, density: 5.243, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1901, discoverer: "Eugène-Anatole Demarçay", nameOrigin: "Europe", uses: ["Red phosphor (TVs)", "Euro banknote security", "Lasers", "Fluorescent lamps"], isotopes: [{ massNumber: 151, abundance: 47.81, halfLife: null }, { massNumber: 153, abundance: 52.19, halfLife: null }], gridRow: 8, gridCol: 8,
  },
  {
    atomicNumber: 64, symbol: "Gd", name: "Gadolinium", atomicMass: 157.25, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²", electronShells: [2, 8, 18, 25, 9, 2], electronegativity: 1.2, atomicRadius: 233, ionizationEnergy: 593, electronAffinity: -50, meltingPoint: 1585, boilingPoint: 3546, density: 7.895, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1880, discoverer: "Jean Charles Galissard de Marignac", nameOrigin: "Mineral gadolinite (Johan Gadolin)", uses: ["MRI contrast agent", "Nuclear reactors", "Magnets", "Microwave applications"], isotopes: [{ massNumber: 152, abundance: 0.20, halfLife: null }, { massNumber: 154, abundance: 2.18, halfLife: null }, { massNumber: 155, abundance: 14.80, halfLife: null }, { massNumber: 156, abundance: 20.47, halfLife: null }, { massNumber: 157, abundance: 15.65, halfLife: null }, { massNumber: 158, abundance: 24.84, halfLife: null }, { massNumber: 160, abundance: 21.86, halfLife: null }], gridRow: 8, gridCol: 9,
  },
  {
    atomicNumber: 65, symbol: "Tb", name: "Terbium", atomicMass: 158.93, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f⁹ 6s²", electronShells: [2, 8, 18, 27, 8, 2], electronegativity: 1.2, atomicRadius: 225, ionizationEnergy: 566, electronAffinity: -50, meltingPoint: 1629, boilingPoint: 3503, density: 8.229, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1843, discoverer: "Carl Gustaf Mosander", nameOrigin: "Ytterby, Sweden", uses: ["Green phosphors", "Sonar systems", "Fuel cells", "Fluorescent lamps"], isotopes: [{ massNumber: 159, abundance: 100, halfLife: null }], gridRow: 8, gridCol: 10,
  },
  {
    atomicNumber: 66, symbol: "Dy", name: "Dysprosium", atomicMass: 162.5, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹⁰ 6s²", electronShells: [2, 8, 18, 28, 8, 2], electronegativity: 1.22, atomicRadius: 228, ionizationEnergy: 573, electronAffinity: -50, meltingPoint: 1680, boilingPoint: 2840, density: 8.55, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1886, discoverer: "Paul Emile Lecoq de Boisbaudran", nameOrigin: "Greek 'dysprositos' — hard to get", uses: ["Magnets (NdFeB additive)", "Nuclear reactors", "Lasers", "Data storage"], isotopes: [{ massNumber: 156, abundance: 0.06, halfLife: null }, { massNumber: 158, abundance: 0.10, halfLife: null }, { massNumber: 160, abundance: 2.34, halfLife: null }, { massNumber: 161, abundance: 18.91, halfLife: null }, { massNumber: 162, abundance: 25.51, halfLife: null }, { massNumber: 163, abundance: 24.90, halfLife: null }, { massNumber: 164, abundance: 28.18, halfLife: null }], gridRow: 8, gridCol: 11,
  },
  {
    atomicNumber: 67, symbol: "Ho", name: "Holmium", atomicMass: 164.93, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹¹ 6s²", electronShells: [2, 8, 18, 29, 8, 2], electronegativity: 1.23, atomicRadius: 226, ionizationEnergy: 581, electronAffinity: -50, meltingPoint: 1734, boilingPoint: 2993, density: 8.795, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1878, discoverer: "Marc Delafontaine & Jacques-Louis Soret", nameOrigin: "Latin 'Holmia' — Stockholm", uses: ["Strongest magnets", "Nuclear reactors", "Lasers", "Magnetic flux concentrators"], isotopes: [{ massNumber: 165, abundance: 100, halfLife: null }], gridRow: 8, gridCol: 12,
  },
  {
    atomicNumber: 68, symbol: "Er", name: "Erbium", atomicMass: 167.26, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹² 6s²", electronShells: [2, 8, 18, 30, 8, 2], electronegativity: 1.24, atomicRadius: 226, ionizationEnergy: 589, electronAffinity: -50, meltingPoint: 1802, boilingPoint: 3141, density: 9.066, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1842, discoverer: "Carl Gustaf Mosander", nameOrigin: "Ytterby, Sweden", uses: ["Fiber optic amplifiers", "Lasers", "Nuclear technology", "Pink glass coloring"], isotopes: [{ massNumber: 162, abundance: 0.14, halfLife: null }, { massNumber: 164, abundance: 1.60, halfLife: null }, { massNumber: 166, abundance: 33.50, halfLife: null }, { massNumber: 167, abundance: 22.87, halfLife: null }, { massNumber: 168, abundance: 26.98, halfLife: null }, { massNumber: 170, abundance: 14.91, halfLife: null }], gridRow: 8, gridCol: 13,
  },
  {
    atomicNumber: 69, symbol: "Tm", name: "Thulium", atomicMass: 168.93, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹³ 6s²", electronShells: [2, 8, 18, 31, 8, 2], electronegativity: 1.25, atomicRadius: 222, ionizationEnergy: 597, electronAffinity: -50, meltingPoint: 1818, boilingPoint: 2223, density: 9.321, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1879, discoverer: "Per Teodor Cleve", nameOrigin: "Thule — ancient name for Scandinavia", uses: ["Portable X-ray devices", "Lasers", "High-temperature superconductors", "Euro banknotes"], isotopes: [{ massNumber: 169, abundance: 100, halfLife: null }], gridRow: 8, gridCol: 14,
  },
  {
    atomicNumber: 70, symbol: "Yb", name: "Ytterbium", atomicMass: 173.05, category: "lanthanide", block: "f", group: null, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 6s²", electronShells: [2, 8, 18, 32, 8, 2], electronegativity: 1.1, atomicRadius: 222, ionizationEnergy: 603, electronAffinity: -50, meltingPoint: 1097, boilingPoint: 1469, density: 6.965, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1878, discoverer: "Jean Charles Galissard de Marignac", nameOrigin: "Ytterby, Sweden", uses: ["Atomic clocks", "Lasers", "Stress gauges", "Solar cells"], isotopes: [{ massNumber: 168, abundance: 0.13, halfLife: null }, { massNumber: 170, abundance: 3.04, halfLife: null }, { massNumber: 171, abundance: 14.28, halfLife: null }, { massNumber: 172, abundance: 21.83, halfLife: null }, { massNumber: 173, abundance: 16.13, halfLife: null }, { massNumber: 174, abundance: 31.83, halfLife: null }, { massNumber: 176, abundance: 12.76, halfLife: null }], gridRow: 8, gridCol: 15,
  },
  {
    atomicNumber: 71, symbol: "Lu", name: "Lutetium", atomicMass: 174.97, category: "lanthanide", block: "d", group: null, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²", electronShells: [2, 8, 18, 32, 9, 2], electronegativity: 1.27, atomicRadius: 217, ionizationEnergy: 524, electronAffinity: -50, meltingPoint: 1925, boilingPoint: 3675, density: 9.84, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1907, discoverer: "Georges Urbain & Carl Auer von Welsbach", nameOrigin: "Latin 'Lutetia' — Paris", uses: ["PET scan detectors", "Catalysts", "LED phosphors", "Research"], isotopes: [{ massNumber: 175, abundance: 97.41, halfLife: null }, { massNumber: 176, abundance: 2.59, halfLife: "37.6 billion years" }], gridRow: 8, gridCol: 16,
  },
  // Period 6 d-block and p-block
  {
    atomicNumber: 72, symbol: "Hf", name: "Hafnium", atomicMass: 178.49, category: "transition-metal", block: "d", group: 4, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²", electronShells: [2, 8, 18, 32, 10, 2], electronegativity: 1.3, atomicRadius: 208, ionizationEnergy: 659, electronAffinity: 0, meltingPoint: 2506, boilingPoint: 4876, density: 13.31, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1923, discoverer: "Dirk Coster & George de Hevesy", nameOrigin: "Latin 'Hafnia' — Copenhagen", uses: ["Nuclear reactors", "Jet engines", "Plasma cutting", "Microprocessors"], isotopes: [{ massNumber: 174, abundance: 0.16, halfLife: null }, { massNumber: 176, abundance: 5.26, halfLife: null }, { massNumber: 177, abundance: 18.60, halfLife: null }, { massNumber: 178, abundance: 27.28, halfLife: null }, { massNumber: 179, abundance: 13.62, halfLife: null }, { massNumber: 180, abundance: 35.08, halfLife: null }], gridRow: 5, gridCol: 3,
  },
  {
    atomicNumber: 73, symbol: "Ta", name: "Tantalum", atomicMass: 180.95, category: "transition-metal", block: "d", group: 5, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²", electronShells: [2, 8, 18, 32, 11, 2], electronegativity: 1.5, atomicRadius: 200, ionizationEnergy: 761, electronAffinity: -31, meltingPoint: 3290, boilingPoint: 5731, density: 16.654, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1802, discoverer: "Anders Gustaf Ekeberg", nameOrigin: "Greek 'Tantalos' — mythological", uses: ["Capacitors", "Surgical implants", "Jet engines", "Chemical equipment"], isotopes: [{ massNumber: 180, abundance: 0.012, halfLife: null }, { massNumber: 181, abundance: 99.988, halfLife: null }], gridRow: 5, gridCol: 4,
  },
  {
    atomicNumber: 74, symbol: "W", name: "Tungsten", atomicMass: 183.84, category: "transition-metal", block: "d", group: 6, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²", electronShells: [2, 8, 18, 32, 12, 2], electronegativity: 2.36, atomicRadius: 193, ionizationEnergy: 770, electronAffinity: -79, meltingPoint: 3695, boilingPoint: 5828, density: 19.25, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1783, discoverer: "Juan José Elhuyar & Fausto Elhuyar", nameOrigin: "Swedish 'tung sten' — heavy stone; symbol from German 'Wolfram'", uses: ["Light bulb filaments", "Cutting tools", "Armor-piercing ammo", "Jewelry"], isotopes: [{ massNumber: 180, abundance: 0.12, halfLife: null }, { massNumber: 182, abundance: 26.50, halfLife: null }, { massNumber: 183, abundance: 14.31, halfLife: null }, { massNumber: 184, abundance: 30.64, halfLife: null }, { massNumber: 186, abundance: 28.43, halfLife: null }], gridRow: 5, gridCol: 5,
  },
  {
    atomicNumber: 75, symbol: "Re", name: "Rhenium", atomicMass: 186.21, category: "transition-metal", block: "d", group: 7, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²", electronShells: [2, 8, 18, 32, 13, 2], electronegativity: 1.9, atomicRadius: 188, ionizationEnergy: 760, electronAffinity: -15, meltingPoint: 3459, boilingPoint: 5869, density: 21.02, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1925, discoverer: "Walter Noddack, Ida Noddack & Otto Berg", nameOrigin: "Latin 'Rhenus' — Rhine river", uses: ["Jet engine superalloys", "Catalysts", "Thermocouples", "Electrical contacts"], isotopes: [{ massNumber: 185, abundance: 37.40, halfLife: null }, { massNumber: 187, abundance: 62.60, halfLife: null }], gridRow: 5, gridCol: 6,
  },
  {
    atomicNumber: 76, symbol: "Os", name: "Osmium", atomicMass: 190.23, category: "transition-metal", block: "d", group: 8, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²", electronShells: [2, 8, 18, 32, 14, 2], electronegativity: 2.2, atomicRadius: 185, ionizationEnergy: 840, electronAffinity: -106, meltingPoint: 3306, boilingPoint: 5285, density: 22.587, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1803, discoverer: "Smithson Tennant", nameOrigin: "Greek 'osme' — smell", uses: ["Fountain pen tips", "Electrical contacts", "Fingerprint detection", "Catalysts"], isotopes: [{ massNumber: 184, abundance: 0.02, halfLife: null }, { massNumber: 186, abundance: 1.59, halfLife: null }, { massNumber: 187, abundance: 1.96, halfLife: null }, { massNumber: 188, abundance: 13.24, halfLife: null }, { massNumber: 189, abundance: 16.15, halfLife: null }, { massNumber: 190, abundance: 26.26, halfLife: null }, { massNumber: 192, abundance: 40.78, halfLife: null }], gridRow: 5, gridCol: 7,
  },
  {
    atomicNumber: 77, symbol: "Ir", name: "Iridium", atomicMass: 192.22, category: "transition-metal", block: "d", group: 9, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²", electronShells: [2, 8, 18, 32, 15, 2], electronegativity: 2.2, atomicRadius: 180, ionizationEnergy: 880, electronAffinity: -151, meltingPoint: 2739, boilingPoint: 4701, density: 22.562, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1803, discoverer: "Smithson Tennant", nameOrigin: "Greek 'iris' — rainbow", uses: ["Spark plugs", "Crucibles", "Kilogram standard", "Satellites"], isotopes: [{ massNumber: 191, abundance: 37.3, halfLife: null }, { massNumber: 193, abundance: 62.7, halfLife: null }], gridRow: 5, gridCol: 8,
  },
  {
    atomicNumber: 78, symbol: "Pt", name: "Platinum", atomicMass: 195.08, category: "transition-metal", block: "d", group: 10, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹", electronShells: [2, 8, 18, 32, 17, 1], electronegativity: 2.28, atomicRadius: 177, ionizationEnergy: 870, electronAffinity: -205, meltingPoint: 2041.4, boilingPoint: 4098, density: 21.46, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1735, discoverer: "Antonio de Ulloa", nameOrigin: "Spanish 'platina' — little silver", uses: ["Catalytic converters", "Jewelry", "Chemotherapy drugs", "Electronics"], isotopes: [{ massNumber: 190, abundance: 0.01, halfLife: null }, { massNumber: 192, abundance: 0.78, halfLife: null }, { massNumber: 194, abundance: 32.97, halfLife: null }, { massNumber: 195, abundance: 33.83, halfLife: null }, { massNumber: 196, abundance: 25.24, halfLife: null }, { massNumber: 198, abundance: 7.16, halfLife: null }], gridRow: 5, gridCol: 9,
  },
  {
    atomicNumber: 79, symbol: "Au", name: "Gold", atomicMass: 196.97, category: "transition-metal", block: "d", group: 11, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹", electronShells: [2, 8, 18, 32, 18, 1], electronegativity: 2.54, atomicRadius: 174, ionizationEnergy: 890, electronAffinity: -223, meltingPoint: 1337.33, boilingPoint: 3129, density: 19.282, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Anglo-Saxon 'gold'; symbol from Latin 'aurum'", uses: ["Jewelry", "Currency/investment", "Electronics", "Dentistry", "Aerospace"], isotopes: [{ massNumber: 197, abundance: 100, halfLife: null }], gridRow: 5, gridCol: 10,
  },
  {
    atomicNumber: 80, symbol: "Hg", name: "Mercury", atomicMass: 200.59, category: "transition-metal", block: "d", group: 12, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²", electronShells: [2, 8, 18, 32, 18, 2], electronegativity: 2.0, atomicRadius: 171, ionizationEnergy: 1007, electronAffinity: 0, meltingPoint: 234.32, boilingPoint: 629.88, density: 13.534, stateAtRT: "liquid", crystalStructure: "rhombohedral", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Planet Mercury; symbol from Latin 'hydrargyrum' — liquid silver", uses: ["Thermometers", "Barometers", "Fluorescent lamps", "Dental amalgams"], isotopes: [{ massNumber: 196, abundance: 0.15, halfLife: null }, { massNumber: 198, abundance: 9.97, halfLife: null }, { massNumber: 199, abundance: 16.87, halfLife: null }, { massNumber: 200, abundance: 23.10, halfLife: null }, { massNumber: 201, abundance: 13.18, halfLife: null }, { massNumber: 202, abundance: 29.86, halfLife: null }, { massNumber: 204, abundance: 6.87, halfLife: null }], gridRow: 5, gridCol: 11,
  },
  {
    atomicNumber: 81, symbol: "Tl", name: "Thallium", atomicMass: 204.38, category: "post-transition-metal", block: "p", group: 13, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", electronShells: [2, 8, 18, 32, 18, 3], electronegativity: 1.62, atomicRadius: 156, ionizationEnergy: 589, electronAffinity: -19, meltingPoint: 577, boilingPoint: 1746, density: 11.85, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1861, discoverer: "William Crookes", nameOrigin: "Greek 'thallos' — green shoot", uses: ["Rat poison (historic)", "Electronics", "Superconductors", "Optics"], isotopes: [{ massNumber: 203, abundance: 29.52, halfLife: null }, { massNumber: 205, abundance: 70.48, halfLife: null }], gridRow: 5, gridCol: 12,
  },
  {
    atomicNumber: 82, symbol: "Pb", name: "Lead", atomicMass: 207.2, category: "post-transition-metal", block: "p", group: 14, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", electronShells: [2, 8, 18, 32, 18, 4], electronegativity: 2.33, atomicRadius: 154, ionizationEnergy: 716, electronAffinity: -35, meltingPoint: 600.61, boilingPoint: 2022, density: 11.342, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: "Ancient", discoverer: null, nameOrigin: "Anglo-Saxon 'lead'; symbol from Latin 'plumbum'", uses: ["Batteries", "Radiation shielding", "Ammunition", "Solder (historic)"], isotopes: [{ massNumber: 204, abundance: 1.4, halfLife: null }, { massNumber: 206, abundance: 24.1, halfLife: null }, { massNumber: 207, abundance: 22.1, halfLife: null }, { massNumber: 208, abundance: 52.4, halfLife: null }], gridRow: 5, gridCol: 13,
  },
  {
    atomicNumber: 83, symbol: "Bi", name: "Bismuth", atomicMass: 208.98, category: "post-transition-metal", block: "p", group: 15, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", electronShells: [2, 8, 18, 32, 18, 5], electronegativity: 2.02, atomicRadius: 143, ionizationEnergy: 703, electronAffinity: -91, meltingPoint: 544.55, boilingPoint: 1837, density: 9.807, stateAtRT: "solid", crystalStructure: "rhombohedral", yearDiscovered: 1753, discoverer: "Claude François Geoffroy", nameOrigin: "German 'Wismuth' — white mass", uses: ["Pepto-Bismol", "Cosmetics", "Fire sprinklers", "Lead-free shot"], isotopes: [{ massNumber: 209, abundance: 100, halfLife: "1.9×10¹⁹ years" }], gridRow: 5, gridCol: 14,
  },
  {
    atomicNumber: 84, symbol: "Po", name: "Polonium", atomicMass: 209, category: "post-transition-metal", block: "p", group: 16, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", electronShells: [2, 8, 18, 32, 18, 6], electronegativity: 2.0, atomicRadius: 135, ionizationEnergy: 812, electronAffinity: -183, meltingPoint: 527, boilingPoint: 1235, density: 9.32, stateAtRT: "solid", crystalStructure: "simple-cubic", yearDiscovered: 1898, discoverer: "Marie & Pierre Curie", nameOrigin: "Latin 'Polonia' — Poland", uses: ["Anti-static devices", "Neutron sources", "Satellite power", "Research"], isotopes: [{ massNumber: 209, abundance: null, halfLife: "125 years" }, { massNumber: 210, abundance: null, halfLife: "138.4 days" }], gridRow: 5, gridCol: 15,
  },
  {
    atomicNumber: 85, symbol: "At", name: "Astatine", atomicMass: 210, category: "halogen", block: "p", group: 17, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", electronShells: [2, 8, 18, 32, 18, 7], electronegativity: 2.2, atomicRadius: 127, ionizationEnergy: 920, electronAffinity: -270, meltingPoint: 575, boilingPoint: 610, density: 7, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1940, discoverer: "Dale R. Corson, Kenneth Ross MacKenzie & Emilio Segrè", nameOrigin: "Greek 'astatos' — unstable", uses: ["Cancer treatment (alpha therapy)", "Research"], isotopes: [{ massNumber: 210, abundance: null, halfLife: "8.1 hours" }, { massNumber: 211, abundance: null, halfLife: "7.2 hours" }], gridRow: 5, gridCol: 16,
  },
  {
    atomicNumber: 86, symbol: "Rn", name: "Radon", atomicMass: 222, category: "noble-gas", block: "p", group: 18, period: 6, electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", electronShells: [2, 8, 18, 32, 18, 8], electronegativity: null, atomicRadius: 120, ionizationEnergy: 1037, electronAffinity: 0, meltingPoint: 202, boilingPoint: 211.3, density: 0.00973, stateAtRT: "gas", crystalStructure: "fcc", yearDiscovered: 1900, discoverer: "Friedrich Ernst Dorn", nameOrigin: "From radium", uses: ["Cancer treatment (historic)", "Earthquake prediction research", "Radon testing"], isotopes: [{ massNumber: 220, abundance: null, halfLife: "55.6 seconds" }, { massNumber: 222, abundance: null, halfLife: "3.82 days" }], gridRow: 5, gridCol: 17,
  },

  // ═══════════════════════════════════════════
  // Period 7
  // ═══════════════════════════════════════════
  {
    atomicNumber: 87, symbol: "Fr", name: "Francium", atomicMass: 223, category: "alkali-metal", block: "s", group: 1, period: 7, electronConfiguration: "[Rn] 7s¹", electronShells: [2, 8, 18, 32, 18, 8, 1], electronegativity: 0.7, atomicRadius: 348, ionizationEnergy: 380, electronAffinity: -47, meltingPoint: 300, boilingPoint: 950, density: 1.87, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1939, discoverer: "Marguerite Perey", nameOrigin: "France", uses: ["Research only — too radioactive and rare for practical use"], isotopes: [{ massNumber: 223, abundance: null, halfLife: "22 minutes" }], gridRow: 6, gridCol: 0,
  },
  {
    atomicNumber: 88, symbol: "Ra", name: "Radium", atomicMass: 226, category: "alkaline-earth-metal", block: "s", group: 2, period: 7, electronConfiguration: "[Rn] 7s²", electronShells: [2, 8, 18, 32, 18, 8, 2], electronegativity: 0.9, atomicRadius: 283, ionizationEnergy: 509, electronAffinity: 0, meltingPoint: 973, boilingPoint: 2010, density: 5.5, stateAtRT: "solid", crystalStructure: "bcc", yearDiscovered: 1898, discoverer: "Marie & Pierre Curie", nameOrigin: "Latin 'radius' — ray", uses: ["Cancer treatment (historic)", "Luminous paint (historic)", "Research"], isotopes: [{ massNumber: 226, abundance: null, halfLife: "1600 years" }, { massNumber: 228, abundance: null, halfLife: "5.75 years" }], gridRow: 6, gridCol: 1,
  },
  {
    atomicNumber: 89, symbol: "Ac", name: "Actinium", atomicMass: 227, category: "actinide", block: "f", group: 3, period: 7, electronConfiguration: "[Rn] 6d¹ 7s²", electronShells: [2, 8, 18, 32, 18, 9, 2], electronegativity: 1.1, atomicRadius: 260, ionizationEnergy: 499, electronAffinity: 0, meltingPoint: 1500, boilingPoint: 3500, density: 10.07, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1899, discoverer: "André-Louis Debierne", nameOrigin: "Greek 'aktinos' — ray", uses: ["Neutron source", "Cancer treatment research", "Thermoelectric power"], isotopes: [{ massNumber: 227, abundance: null, halfLife: "21.77 years" }], gridRow: 6, gridCol: 2,
  },
  {
    atomicNumber: 90, symbol: "Th", name: "Thorium", atomicMass: 232.04, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 6d² 7s²", electronShells: [2, 8, 18, 32, 18, 10, 2], electronegativity: 1.3, atomicRadius: 237, ionizationEnergy: 587, electronAffinity: 0, meltingPoint: 2115, boilingPoint: 5061, density: 11.72, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1829, discoverer: "Jöns Jacob Berzelius", nameOrigin: "Thor — Norse god of thunder", uses: ["Nuclear fuel", "Gas mantles", "Aerospace alloys", "Welding electrodes"], isotopes: [{ massNumber: 232, abundance: 100, halfLife: "14.05 billion years" }], gridRow: 9, gridCol: 3,
  },
  {
    atomicNumber: 91, symbol: "Pa", name: "Protactinium", atomicMass: 231.04, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f² 6d¹ 7s²", electronShells: [2, 8, 18, 32, 20, 9, 2], electronegativity: 1.5, atomicRadius: 243, ionizationEnergy: 568, electronAffinity: 0, meltingPoint: 1841, boilingPoint: 4300, density: 15.37, stateAtRT: "solid", crystalStructure: "tetragonal", yearDiscovered: 1913, discoverer: "Kasimir Fajans & Oswald Helmuth Göhring", nameOrigin: "Greek 'protos' — first (parent of actinium)", uses: ["Research only"], isotopes: [{ massNumber: 231, abundance: 100, halfLife: "32,760 years" }], gridRow: 9, gridCol: 4,
  },
  {
    atomicNumber: 92, symbol: "U", name: "Uranium", atomicMass: 238.03, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f³ 6d¹ 7s²", electronShells: [2, 8, 18, 32, 21, 9, 2], electronegativity: 1.38, atomicRadius: 240, ionizationEnergy: 598, electronAffinity: 0, meltingPoint: 1405.3, boilingPoint: 4404, density: 18.95, stateAtRT: "solid", crystalStructure: "orthorhombic", yearDiscovered: 1789, discoverer: "Martin Heinrich Klaproth", nameOrigin: "Planet Uranus", uses: ["Nuclear power", "Nuclear weapons", "Armor-piercing ammo", "Counterweights"], isotopes: [{ massNumber: 234, abundance: 0.005, halfLife: "245,500 years" }, { massNumber: 235, abundance: 0.72, halfLife: "703.8 million years" }, { massNumber: 238, abundance: 99.27, halfLife: "4.468 billion years" }], gridRow: 9, gridCol: 5,
  },
  {
    atomicNumber: 93, symbol: "Np", name: "Neptunium", atomicMass: 237, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²", electronShells: [2, 8, 18, 32, 22, 9, 2], electronegativity: 1.36, atomicRadius: 221, ionizationEnergy: 605, electronAffinity: 0, meltingPoint: 917, boilingPoint: 4175, density: 20.45, stateAtRT: "solid", crystalStructure: "orthorhombic", yearDiscovered: 1940, discoverer: "Edwin McMillan & Philip Abelson", nameOrigin: "Planet Neptune", uses: ["Neutron detection", "Nuclear weapons research", "Precursor to Pu-238"], isotopes: [{ massNumber: 237, abundance: null, halfLife: "2.14 million years" }], gridRow: 9, gridCol: 6,
  },
  {
    atomicNumber: 94, symbol: "Pu", name: "Plutonium", atomicMass: 244, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f⁶ 7s²", electronShells: [2, 8, 18, 32, 24, 8, 2], electronegativity: 1.28, atomicRadius: 243, ionizationEnergy: 585, electronAffinity: 0, meltingPoint: 912.5, boilingPoint: 3505, density: 19.84, stateAtRT: "solid", crystalStructure: "monoclinic", yearDiscovered: 1940, discoverer: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy & Arthur Wahl", nameOrigin: "Dwarf planet Pluto", uses: ["Nuclear weapons", "Nuclear power", "RTG space power", "Pacemaker batteries (historic)"], isotopes: [{ massNumber: 238, abundance: null, halfLife: "87.7 years" }, { massNumber: 239, abundance: null, halfLife: "24,110 years" }, { massNumber: 244, abundance: null, halfLife: "80.8 million years" }], gridRow: 9, gridCol: 7,
  },
  {
    atomicNumber: 95, symbol: "Am", name: "Americium", atomicMass: 243, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f⁷ 7s²", electronShells: [2, 8, 18, 32, 25, 8, 2], electronegativity: 1.3, atomicRadius: 244, ionizationEnergy: 578, electronAffinity: 0, meltingPoint: 1449, boilingPoint: 2880, density: 13.69, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1944, discoverer: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan & Albert Ghiorso", nameOrigin: "Americas", uses: ["Smoke detectors", "Neutron sources", "Research"], isotopes: [{ massNumber: 241, abundance: null, halfLife: "432.2 years" }, { massNumber: 243, abundance: null, halfLife: "7,370 years" }], gridRow: 9, gridCol: 8,
  },
  {
    atomicNumber: 96, symbol: "Cm", name: "Curium", atomicMass: 247, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²", electronShells: [2, 8, 18, 32, 25, 9, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 581, electronAffinity: 0, meltingPoint: 1613, boilingPoint: 3383, density: 13.51, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1944, discoverer: "Glenn T. Seaborg, Ralph A. James & Albert Ghiorso", nameOrigin: "Marie & Pierre Curie", uses: ["Mars rover power (alpha spectrometer)", "Pacemaker power (historic)", "Research"], isotopes: [{ massNumber: 247, abundance: null, halfLife: "15.6 million years" }], gridRow: 9, gridCol: 9,
  },
  {
    atomicNumber: 97, symbol: "Bk", name: "Berkelium", atomicMass: 247, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f⁹ 7s²", electronShells: [2, 8, 18, 32, 27, 8, 2], electronegativity: 1.3, atomicRadius: 244, ionizationEnergy: 601, electronAffinity: 0, meltingPoint: 1259, boilingPoint: 2900, density: 14.79, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1949, discoverer: "Stanley G. Thompson, Albert Ghiorso & Glenn T. Seaborg", nameOrigin: "Berkeley, California", uses: ["Research only — target material for producing heavier elements"], isotopes: [{ massNumber: 247, abundance: null, halfLife: "1,380 years" }, { massNumber: 249, abundance: null, halfLife: "330 days" }], gridRow: 9, gridCol: 10,
  },
  {
    atomicNumber: 98, symbol: "Cf", name: "Californium", atomicMass: 251, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f¹⁰ 7s²", electronShells: [2, 8, 18, 32, 28, 8, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 608, electronAffinity: 0, meltingPoint: 1173, boilingPoint: 1743, density: 15.1, stateAtRT: "solid", crystalStructure: "hcp", yearDiscovered: 1950, discoverer: "Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso & Glenn T. Seaborg", nameOrigin: "California & UC Berkeley", uses: ["Neutron source", "Metal detection", "Oil well logging", "Nuclear reactor startup"], isotopes: [{ massNumber: 249, abundance: null, halfLife: "351 years" }, { massNumber: 252, abundance: null, halfLife: "2.645 years" }], gridRow: 9, gridCol: 11,
  },
  {
    atomicNumber: 99, symbol: "Es", name: "Einsteinium", atomicMass: 252, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f¹¹ 7s²", electronShells: [2, 8, 18, 32, 29, 8, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 619, electronAffinity: 0, meltingPoint: 1133, boilingPoint: 1269, density: 8.84, stateAtRT: "solid", crystalStructure: "fcc", yearDiscovered: 1952, discoverer: "Albert Ghiorso et al.", nameOrigin: "Albert Einstein", uses: ["Research only"], isotopes: [{ massNumber: 252, abundance: null, halfLife: "471.7 days" }, { massNumber: 253, abundance: null, halfLife: "20.47 days" }], gridRow: 9, gridCol: 12,
  },
  {
    atomicNumber: 100, symbol: "Fm", name: "Fermium", atomicMass: 257, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f¹² 7s²", electronShells: [2, 8, 18, 32, 30, 8, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 627, electronAffinity: 0, meltingPoint: 1800, boilingPoint: null, density: null, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1952, discoverer: "Albert Ghiorso et al.", nameOrigin: "Enrico Fermi", uses: ["Research only"], isotopes: [{ massNumber: 257, abundance: null, halfLife: "100.5 days" }], gridRow: 9, gridCol: 13,
  },
  {
    atomicNumber: 101, symbol: "Md", name: "Mendelevium", atomicMass: 258, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f¹³ 7s²", electronShells: [2, 8, 18, 32, 31, 8, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 635, electronAffinity: 0, meltingPoint: 1100, boilingPoint: null, density: null, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1955, discoverer: "Albert Ghiorso, Bernard G. Harvey, Gregory R. Choppin, Stanley G. Thompson & Glenn T. Seaborg", nameOrigin: "Dmitri Mendeleev", uses: ["Research only"], isotopes: [{ massNumber: 258, abundance: null, halfLife: "51.5 days" }], gridRow: 9, gridCol: 14,
  },
  {
    atomicNumber: 102, symbol: "No", name: "Nobelium", atomicMass: 259, category: "actinide", block: "f", group: null, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 7s²", electronShells: [2, 8, 18, 32, 32, 8, 2], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 642, electronAffinity: 0, meltingPoint: 1100, boilingPoint: null, density: null, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1958, discoverer: "Albert Ghiorso, Torbjørn Sikkeland, John R. Walton & Glenn T. Seaborg", nameOrigin: "Alfred Nobel", uses: ["Research only"], isotopes: [{ massNumber: 259, abundance: null, halfLife: "58 minutes" }], gridRow: 9, gridCol: 15,
  },
  {
    atomicNumber: 103, symbol: "Lr", name: "Lawrencium", atomicMass: 266, category: "actinide", block: "d", group: null, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹", electronShells: [2, 8, 18, 32, 32, 8, 3], electronegativity: 1.3, atomicRadius: 245, ionizationEnergy: 470, electronAffinity: 0, meltingPoint: 1900, boilingPoint: null, density: null, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1961, discoverer: "Albert Ghiorso, Torbjørn Sikkeland, Almon Larsh & Robert Latimer", nameOrigin: "Ernest O. Lawrence", uses: ["Research only"], isotopes: [{ massNumber: 262, abundance: null, halfLife: "3.6 hours" }], gridRow: 9, gridCol: 16,
  },
  // Period 7 d-block and p-block
  {
    atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", atomicMass: 267, category: "transition-metal", block: "d", group: 4, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²", electronShells: [2, 8, 18, 32, 32, 10, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: 580, electronAffinity: 0, meltingPoint: 2400, boilingPoint: 5800, density: 23.2, stateAtRT: "solid", crystalStructure: "unknown", yearDiscovered: 1964, discoverer: "Joint Institute for Nuclear Research (Dubna) & Lawrence Berkeley National Laboratory", nameOrigin: "Ernest Rutherford", uses: ["Research only"], isotopes: [{ massNumber: 267, abundance: null, halfLife: "1.3 hours" }], gridRow: 6, gridCol: 3,
  },
  {
    atomicNumber: 105, symbol: "Db", name: "Dubnium", atomicMass: 268, category: "transition-metal", block: "d", group: 5, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²", electronShells: [2, 8, 18, 32, 32, 11, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 29.3, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1967, discoverer: "Joint Institute for Nuclear Research (Dubna)", nameOrigin: "Dubna, Russia", uses: ["Research only"], isotopes: [{ massNumber: 268, abundance: null, halfLife: "28 hours" }], gridRow: 6, gridCol: 4,
  },
  {
    atomicNumber: 106, symbol: "Sg", name: "Seaborgium", atomicMass: 269, category: "transition-metal", block: "d", group: 6, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²", electronShells: [2, 8, 18, 32, 32, 12, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 35, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1974, discoverer: "Lawrence Berkeley National Laboratory", nameOrigin: "Glenn T. Seaborg", uses: ["Research only"], isotopes: [{ massNumber: 269, abundance: null, halfLife: "3.1 minutes" }], gridRow: 6, gridCol: 5,
  },
  {
    atomicNumber: 107, symbol: "Bh", name: "Bohrium", atomicMass: 270, category: "transition-metal", block: "d", group: 7, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²", electronShells: [2, 8, 18, 32, 32, 13, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 37.1, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1981, discoverer: "Peter Armbruster & Gottfried Münzenberg (GSI Darmstadt)", nameOrigin: "Niels Bohr", uses: ["Research only"], isotopes: [{ massNumber: 270, abundance: null, halfLife: "61 seconds" }], gridRow: 6, gridCol: 6,
  },
  {
    atomicNumber: 108, symbol: "Hs", name: "Hassium", atomicMass: 277, category: "transition-metal", block: "d", group: 8, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²", electronShells: [2, 8, 18, 32, 32, 14, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 40.7, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1984, discoverer: "Peter Armbruster & Gottfried Münzenberg (GSI Darmstadt)", nameOrigin: "Latin 'Hassia' — Hesse, Germany", uses: ["Research only"], isotopes: [{ massNumber: 277, abundance: null, halfLife: "11 seconds" }], gridRow: 6, gridCol: 7,
  },
  {
    atomicNumber: 109, symbol: "Mt", name: "Meitnerium", atomicMass: 278, category: "unknown", block: "d", group: 9, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²", electronShells: [2, 8, 18, 32, 32, 15, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 37.4, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1982, discoverer: "Peter Armbruster & Gottfried Münzenberg (GSI Darmstadt)", nameOrigin: "Lise Meitner", uses: ["Research only"], isotopes: [{ massNumber: 278, abundance: null, halfLife: "7.6 seconds" }], gridRow: 6, gridCol: 8,
  },
  {
    atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", atomicMass: 281, category: "unknown", block: "d", group: 10, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²", electronShells: [2, 8, 18, 32, 32, 16, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 34.8, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1994, discoverer: "Peter Armbruster & Gottfried Münzenberg (GSI Darmstadt)", nameOrigin: "Darmstadt, Germany", uses: ["Research only"], isotopes: [{ massNumber: 281, abundance: null, halfLife: "12.7 seconds" }], gridRow: 6, gridCol: 9,
  },
  {
    atomicNumber: 111, symbol: "Rg", name: "Roentgenium", atomicMass: 282, category: "unknown", block: "d", group: 11, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²", electronShells: [2, 8, 18, 32, 32, 17, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 28.7, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1994, discoverer: "Peter Armbruster & Gottfried Münzenberg (GSI Darmstadt)", nameOrigin: "Wilhelm Conrad Röntgen", uses: ["Research only"], isotopes: [{ massNumber: 282, abundance: null, halfLife: "2.1 minutes" }], gridRow: 6, gridCol: 10,
  },
  {
    atomicNumber: 112, symbol: "Cn", name: "Copernicium", atomicMass: 285, category: "unknown", block: "d", group: 12, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²", electronShells: [2, 8, 18, 32, 32, 18, 2], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: null, boilingPoint: null, density: 23.7, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1996, discoverer: "Sigurd Hofmann (GSI Darmstadt)", nameOrigin: "Nicolaus Copernicus", uses: ["Research only"], isotopes: [{ massNumber: 285, abundance: null, halfLife: "29 seconds" }], gridRow: 6, gridCol: 11,
  },
  {
    atomicNumber: 113, symbol: "Nh", name: "Nihonium", atomicMass: 286, category: "unknown", block: "p", group: 13, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", electronShells: [2, 8, 18, 32, 32, 18, 3], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 700, boilingPoint: 1400, density: 16, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 2003, discoverer: "RIKEN (Kosuke Morita)", nameOrigin: "Japanese 'Nihon' — Japan", uses: ["Research only"], isotopes: [{ massNumber: 286, abundance: null, halfLife: "9.5 seconds" }], gridRow: 6, gridCol: 12,
  },
  {
    atomicNumber: 114, symbol: "Fl", name: "Flerovium", atomicMass: 289, category: "unknown", block: "p", group: 14, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", electronShells: [2, 8, 18, 32, 32, 18, 4], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 340, boilingPoint: 420, density: 14, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 1998, discoverer: "Joint Institute for Nuclear Research (Dubna) & LLNL", nameOrigin: "Flerov Laboratory of Nuclear Reactions (Georgy Flyorov)", uses: ["Research only"], isotopes: [{ massNumber: 289, abundance: null, halfLife: "2.6 seconds" }], gridRow: 6, gridCol: 13,
  },
  {
    atomicNumber: 115, symbol: "Mc", name: "Moscovium", atomicMass: 290, category: "unknown", block: "p", group: 15, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", electronShells: [2, 8, 18, 32, 32, 18, 5], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 670, boilingPoint: 1400, density: 13.5, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 2003, discoverer: "Joint Institute for Nuclear Research (Dubna) & LLNL", nameOrigin: "Moscow Oblast, Russia", uses: ["Research only"], isotopes: [{ massNumber: 290, abundance: null, halfLife: "0.65 seconds" }], gridRow: 6, gridCol: 14,
  },
  {
    atomicNumber: 116, symbol: "Lv", name: "Livermorium", atomicMass: 293, category: "unknown", block: "p", group: 16, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", electronShells: [2, 8, 18, 32, 32, 18, 6], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 709, boilingPoint: 1085, density: 12.9, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 2000, discoverer: "Joint Institute for Nuclear Research (Dubna) & LLNL", nameOrigin: "Lawrence Livermore National Laboratory", uses: ["Research only"], isotopes: [{ massNumber: 293, abundance: null, halfLife: "53 milliseconds" }], gridRow: 6, gridCol: 15,
  },
  {
    atomicNumber: 117, symbol: "Ts", name: "Tennessine", atomicMass: 294, category: "unknown", block: "p", group: 17, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", electronShells: [2, 8, 18, 32, 32, 18, 7], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 723, boilingPoint: 883, density: 7.2, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 2010, discoverer: "Joint Institute for Nuclear Research (Dubna) & ORNL", nameOrigin: "Tennessee, USA", uses: ["Research only"], isotopes: [{ massNumber: 294, abundance: null, halfLife: "51 milliseconds" }], gridRow: 6, gridCol: 16,
  },
  {
    atomicNumber: 118, symbol: "Og", name: "Oganesson", atomicMass: 294, category: "unknown", block: "p", group: 18, period: 7, electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", electronShells: [2, 8, 18, 32, 32, 18, 8], electronegativity: null, atomicRadius: null, ionizationEnergy: null, electronAffinity: 0, meltingPoint: 325, boilingPoint: 450, density: 5.0, stateAtRT: "unknown", crystalStructure: "unknown", yearDiscovered: 2002, discoverer: "Joint Institute for Nuclear Research (Dubna) & LLNL", nameOrigin: "Yuri Oganessian", uses: ["Research only"], isotopes: [{ massNumber: 294, abundance: null, halfLife: "0.7 milliseconds" }], gridRow: 6, gridCol: 17,
  },
];

/** Lookup element by atomic number (1-indexed) */
export function getElement(atomicNumber: number): Element | undefined {
  return ELEMENTS.find((e) => e.atomicNumber === atomicNumber);
}

/** Get element state at a given temperature */
export function getElementState(
  element: Element,
  temperatureK: number
): "solid" | "liquid" | "gas" | "unknown" {
  if (element.meltingPoint === null || element.boilingPoint === null) {
    return "unknown";
  }
  if (temperatureK < element.meltingPoint) return "solid";
  if (temperatureK < element.boilingPoint) return "liquid";
  return "gas";
}
